sudo: false
language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - docs/_build
    # Installed language package caches
    - ~/.cabal
    - ~/.ghc
    - ~/.ghc-mod
    - ~/R/Library
    - ~/.julia
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/.bundle
    - $TRAVIS_BUILD_DIR/vendor
    # coala managed data
    - ~/nltk_data
    - ~/.local/share/coala-bears
    # Installed linters
    - ~/infer-linux64-v0.7.0
    - ~/pmd-bin-5.4.1
    - ~/bakalint-0.4.0
    - ~/elm-format-0.18
    - ~/dart-sdk/bin
    - ~/.local/tailor/
    - ~/phpmd

script:
  - pip install git+https://github.com/coala/coala
  - pip install git+https://github.com/coala/coala-bears

after_script:
  # expect exit code 5
  - coala --non-interactive
